import { Vehicle } from '@/domain/vehicles/entities/Vehicle'
import { IVehicleRepository } from '@/domain/vehicles/repositories/IVehicleRepository'
import { CreateVehicleDTO, VehicleDTO } from '../dto'
import { VIN, RegistrationNumber } from '@/domain/vehicles/value-objects'
import { UserContext } from '@/application/shared/types/UserContext'
import { db } from '@/lib/db'

/**
 * Use case for creating a new vehicle
 */
export class CreateVehicleUseCase {
  constructor(private readonly vehicleRepository: IVehicleRepository) {}

  async execute(dto: CreateVehicleDTO, user: UserContext): Promise<VehicleDTO> {
    // Create value objects
    const vin = dto.vin ? VIN.create(dto.vin) : null
    const registrationNumber = dto.registrationNumber
      ? RegistrationNumber.create(dto.registrationNumber)
      : null

    // Validate that at least VIN or registration number is provided
    if (!vin && !registrationNumber) {
      throw new Error('VIN lub numer rejestracyjny jest wymagany')
    }

    // Check for duplicates
    if (vin) {
      const existingByVIN = await this.vehicleRepository.findByVIN(vin.getValue())
      if (existingByVIN) {
        throw new Error('Pojazd o podanym numerze VIN już istnieje')
      }
    }

    if (registrationNumber) {
      const existingByReg = await this.vehicleRepository.findByRegistrationNumber(
        registrationNumber.getValue()
      )
      if (existingByReg) {
        throw new Error('Pojazd o podanym numerze rejestracyjnym już istnieje')
      }
    }

    // Create vehicle entity (ID will be generated by Prisma)
    const vehicle = Vehicle.create({
      id: '', // Empty ID, will be generated by Prisma
      vin,
      registrationNumber,
      firstRegistrationDate: dto.firstRegistrationDate ? new Date(dto.firstRegistrationDate) : null,
      brand: dto.brand || null,
      model: dto.model || null,
      productionYear: dto.productionYear || null,
      infoEkspertId: dto.infoEkspertId || null,
      eurotaxId: dto.eurotaxId || null,
      eurotaxData: dto.eurotaxData || null,
      infoEkspertData: dto.infoEkspertData || null,
      importedFromAbroad: dto.importedFromAbroad ?? false,
      hasValidInspection: dto.hasValidInspection ?? null,
      hasLpgInstallation: dto.hasLpgInstallation ?? null,
      purchaseYear: dto.purchaseYear || null,
      currentMileage: dto.currentMileage || null,
      organizationId: dto.organizationId || user.organizationId || null,
    })

    // Save vehicle
    const savedVehicle = await this.vehicleRepository.create(vehicle)

    // Log activity
    await db.activityLog.create({
      data: {
        userId: user.id,
        action: 'VEHICLE_CREATED',
        entityType: 'Vehicle',
        entityId: savedVehicle.getId(),
        details: {
          vin: savedVehicle.getVIN()?.getValue() || null,
          registrationNumber: savedVehicle.getRegistrationNumber()?.getValue() || null,
        },
      },
    })

    return this.toDTO(savedVehicle)
  }

  private toDTO(vehicle: Vehicle): VehicleDTO {
    return {
      id: vehicle.getId(),
      vin: vehicle.getVIN()?.getValue() || null,
      registrationNumber: vehicle.getRegistrationNumber()?.getValue() || null,
      firstRegistrationDate: vehicle.getFirstRegistrationDate(),
      brand: vehicle.getBrand(),
      model: vehicle.getModel(),
      productionYear: vehicle.getProductionYear(),
      infoEkspertId: vehicle.getInfoEkspertId(),
      eurotaxId: vehicle.getEurotaxId(),
      eurotaxData: vehicle.getEurotaxData(),
      infoEkspertData: vehicle.getInfoEkspertData(),
      importedFromAbroad: vehicle.getImportedFromAbroad(),
      hasValidInspection: vehicle.getHasValidInspection(),
      hasLpgInstallation: vehicle.getHasLpgInstallation(),
      purchaseYear: vehicle.getPurchaseYear(),
      currentMileage: vehicle.getCurrentMileage(),
      organizationId: vehicle.getOrganizationId(),
      createdAt: vehicle.getCreatedAt(),
      updatedAt: vehicle.getUpdatedAt(),
    }
  }
}

