import { Deal } from '@/domain/deals/entities/Deal'
import { IDealRepository } from '@/domain/deals/repositories/IDealRepository'
import { CreateDealDTO, DealDTO } from '../dto'
import { DealValue, Probability, DealStage } from '@/domain/deals/value-objects'
import { DealStage as PrismaDealStage } from '@prisma/client'
import { UserContext } from '@/application/shared/types/UserContext'
import { db } from '@/lib/db'

/**
 * Use case for creating a new deal
 */
export class CreateDealUseCase {
  constructor(private readonly dealRepository: IDealRepository) {}

  async execute(dto: CreateDealDTO, user: UserContext): Promise<DealDTO> {
    // Validate client exists
    const client = await db.client.findUnique({
      where: { id: dto.clientId },
    })

    if (!client) {
      throw new Error('Klient nie znaleziony')
    }

    // Check authorization - user must have access to client
    if (user.role !== 'ADMIN' && client.assignedTo !== user.id) {
      // Check if client is shared with user's groups
      const hasGroupAccess = await db.client.findFirst({
        where: {
          id: dto.clientId,
          sharedGroups: {
            some: {
              users: {
                some: {
                  userId: user.id,
                },
              },
            },
          },
        },
      })

      if (!hasGroupAccess) {
        throw new Error('Brak uprawnień do tego klienta')
      }
    }

    // Create value objects
    const dealValue = DealValue.create(dto.value, dto.currency || 'PLN')
    const probability = Probability.create(dto.probability || 0)
    const stage = DealStage.create(dto.stage || PrismaDealStage.INITIAL_CONTACT)

    // Create deal entity (ID will be generated by Prisma)
    const deal = Deal.create({
      id: '', // Empty ID, will be generated by Prisma
      clientId: dto.clientId,
      value: dealValue,
      probability,
      stage,
      expectedCloseDate: dto.expectedCloseDate ? new Date(dto.expectedCloseDate) : null,
      notes: dto.notes || null,
    })

    // Save deal
    const savedDeal = await this.dealRepository.create(deal)

    // Log activity
    await db.activityLog.create({
      data: {
        userId: user.id,
        action: 'DEAL_CREATED',
        entityType: 'Deal',
        entityId: savedDeal.getId(),
        details: {
          clientId: savedDeal.getClientId(),
          value: savedDeal.getValue().getAmount(),
          currency: savedDeal.getValue().getCurrency(),
          stage: savedDeal.getStage().getValue(),
        },
      },
    })

    // Handle shared groups if provided
    if (dto.sharedGroupIds && dto.sharedGroupIds.length > 0) {
      await db.deal.update({
        where: { id: savedDeal.getId() },
        data: {
          sharedGroups: {
            connect: dto.sharedGroupIds.map((id) => ({ id })),
          },
        },
      })
    }

    return this.toDTO(savedDeal)
  }

  private toDTO(deal: Deal): DealDTO {
    return {
      id: deal.getId(),
      clientId: deal.getClientId(),
      value: deal.getValue().getAmount(),
      currency: deal.getValue().getCurrency(),
      probability: deal.getProbability().getValue(),
      stage: deal.getStage().getValue(),
      expectedCloseDate: deal.getExpectedCloseDate(),
      notes: deal.getNotes(),
      createdAt: deal.getCreatedAt(),
      updatedAt: deal.getUpdatedAt(),
    }
  }
}

