import { InsuranceAgent } from '@/domain/insurance-agents/entities/InsuranceAgent'
import { IInsuranceAgentRepository } from '@/domain/insurance-agents/repositories/IInsuranceAgentRepository'
import { CreateInsuranceAgentDTO, InsuranceAgentDTO } from '../dto'
import { UserContext } from '@/application/shared/types/UserContext'
import { db } from '@/lib/db'

/**
 * Use case for creating a new insurance agent
 */
export class CreateInsuranceAgentUseCase {
  constructor(private readonly agentRepository: IInsuranceAgentRepository) {}

  async execute(dto: CreateInsuranceAgentDTO, user: UserContext): Promise<InsuranceAgentDTO> {
    // Check if agent already exists for this user
    const existingAgent = await this.agentRepository.findByUserId(dto.userId)
    if (existingAgent) {
      throw new Error('Agent ubezpieczeniowy już istnieje dla tego użytkownika')
    }

    // Create agent entity
    const agent = InsuranceAgent.create({
      id: '', // Empty ID, will be generated by Prisma
      userId: dto.userId,
      licenseNumber: dto.licenseNumber || null,
      settings: dto.settings || {},
      isActive: dto.isActive ?? true,
      organizationId: dto.organizationId || user.organizationId || null,
    })

    // Save agent
    const savedAgent = await this.agentRepository.create(agent)

    // Log activity
    await db.activityLog.create({
      data: {
        userId: user.id,
        action: 'INSURANCE_AGENT_CREATED',
        entityType: 'InsuranceAgent',
        entityId: savedAgent.getId(),
        details: {
          userId: savedAgent.getUserId(),
        },
      },
    })

    return this.toDTO(savedAgent)
  }

  private toDTO(agent: InsuranceAgent): InsuranceAgentDTO {
    const data = agent.toPersistence()
    return {
      id: data.id,
      userId: data.userId,
      licenseNumber: data.licenseNumber,
      settings: agent.getSettings(),
      isActive: data.isActive,
      organizationId: data.organizationId,
      createdAt: data.createdAt,
      updatedAt: data.updatedAt,
    }
  }
}

