import { Policy } from '@/domain/policies/entities/Policy'
import { IPolicyRepository } from '@/domain/policies/repositories/IPolicyRepository'
import { PolicyNumber } from '@/domain/policies/value-objects'
import { CreatePolicyDTO, PolicyDTO } from '../dto'
import { UserContext } from '@/application/shared/types/UserContext'
import { db } from '@/lib/db'

/**
 * Use case for creating a new policy
 */
export class CreatePolicyUseCase {
  constructor(private readonly policyRepository: IPolicyRepository) {}

  async execute(dto: CreatePolicyDTO, user: UserContext): Promise<PolicyDTO> {
    // Create value objects
    const policyNumber = PolicyNumber.create(dto.policyNumber)
    if (!policyNumber) {
      throw new Error('Nieprawidłowy numer polisy')
    }

    // Create policy entity
    const policy = Policy.create({
      id: '', // Empty ID, will be generated by Prisma
      policyNumber,
      issueDate: new Date(dto.issueDate),
      validFrom: new Date(dto.validFrom),
      validTo: new Date(dto.validTo),
      status: dto.status || 'ACTIVE',
      calculationId: dto.calculationId || null,
      clientId: dto.clientId || null,
      vehicleId: dto.vehicleId || null,
      insuranceCompanyId: dto.insuranceCompanyId,
      agentId: dto.agentId || user.id || null,
      organizationId: dto.organizationId || user.organizationId || null,
      externalId: dto.externalId || null,
      configurationType: dto.configurationType || null,
      leasingCompany: dto.leasingCompany || null,
      creditProvider: dto.creditProvider || null,
      contractNumber: dto.contractNumber || null,
    })

    // Save policy
    const savedPolicy = await this.policyRepository.create(policy)

    // Log activity
    await db.activityLog.create({
      data: {
        userId: user.id,
        action: 'POLICY_CREATED',
        entityType: 'Policy',
        entityId: savedPolicy.getId(),
        details: {
          policyNumber: savedPolicy.getPolicyNumber().getValue(),
          status: savedPolicy.getStatus(),
        },
      },
    })

    return this.toDTO(savedPolicy)
  }

  private toDTO(policy: Policy): PolicyDTO {
    const data = policy.toPersistence()
    return {
      id: data.id,
      policyNumber: data.policyNumber,
      issueDate: data.issueDate,
      validFrom: data.validFrom,
      validTo: data.validTo,
      status: data.status,
      calculationId: data.calculationId,
      clientId: data.clientId,
      vehicleId: data.vehicleId,
      insuranceCompanyId: data.insuranceCompanyId,
      agentId: data.agentId,
      organizationId: data.organizationId,
      externalId: data.externalId,
      syncedAt: data.syncedAt,
      configurationType: data.configurationType,
      leasingCompany: data.leasingCompany,
      creditProvider: data.creditProvider,
      contractNumber: data.contractNumber,
      configurationMetadata: data.configurationMetadata,
      createdAt: data.createdAt,
      updatedAt: data.updatedAt,
    }
  }
}

