import { Calculation } from '@/domain/calculations/entities/Calculation'
import { ICalculationRepository } from '@/domain/calculations/repositories/ICalculationRepository'
import { CreateCalculationDTO, CalculationDTO } from '../dto'
import { PESEL, PostalCode, InsuranceVariant, InsuranceScope } from '@/domain/calculations/value-objects'
import { UserContext } from '@/application/shared/types/UserContext'
import { db } from '@/lib/db'

/**
 * Use case for creating a new calculation
 */
export class CreateCalculationUseCase {
  constructor(private readonly calculationRepository: ICalculationRepository) {}

  async execute(dto: CreateCalculationDTO, user: UserContext): Promise<CalculationDTO> {
    // Create value objects
    const pesel = dto.pesel ? PESEL.create(dto.pesel) : null
    const postalCode = dto.postalCode ? PostalCode.create(dto.postalCode) : null
    const variant = dto.variant ? InsuranceVariant.create(dto.variant) : null
    const scopes = dto.scopes
      ? dto.scopes.map((s) => InsuranceScope.create(s)).filter((s): s is InsuranceScope => s !== null)
      : []

    // Create calculation entity
    const calculation = Calculation.create({
      id: '', // Empty ID, will be generated by Prisma
      pesel,
      firstName: dto.firstName || null,
      lastName: dto.lastName || null,
      previousLastName: dto.previousLastName || null,
      phone: dto.phone || null,
      email: dto.email || null,
      postalCode,
      city: dto.city || null,
      street: dto.street || null,
      houseNumber: dto.houseNumber || null,
      apartmentNumber: dto.apartmentNumber || null,
      correspondenceAddress: dto.correspondenceAddress || null,
      hasDrivingLicense: dto.hasDrivingLicense ?? null,
      drivingLicenseDate: dto.drivingLicenseDate ? new Date(dto.drivingLicenseDate) : null,
      occupation: dto.occupation || null,
      maritalStatus: dto.maritalStatus || null,
      hasChildUnder26: dto.hasChildUnder26 ?? null,
      clientId: dto.clientId || null,
      vehicleId: dto.vehicleId || null,
      agentId: dto.agentId || user.id || null,
      organizationId: dto.organizationId || user.organizationId || null,
      status: dto.status || 'DRAFT',
      value: dto.value || null,
      validUntil: dto.validUntil ? new Date(dto.validUntil) : null,
      variant,
      scopes,
    })

    // Save calculation
    const savedCalculation = await this.calculationRepository.create(calculation)

    // Log activity
    await db.activityLog.create({
      data: {
        userId: user.id,
        action: 'CALCULATION_CREATED',
        entityType: 'Calculation',
        entityId: savedCalculation.getId(),
        details: {
          status: savedCalculation.getStatus(),
          clientId: savedCalculation.getClientId(),
        },
      },
    })

    return this.toDTO(savedCalculation)
  }

  private toDTO(calculation: Calculation): CalculationDTO {
    const data = calculation.toPersistence()
    return {
      id: data.id,
      pesel: data.pesel,
      firstName: data.firstName,
      lastName: data.lastName,
      previousLastName: data.previousLastName,
      phone: data.phone,
      email: data.email,
      postalCode: data.postalCode,
      city: data.city,
      street: data.street,
      houseNumber: data.houseNumber,
      apartmentNumber: data.apartmentNumber,
      correspondenceAddress: data.correspondenceAddress,
      hasDrivingLicense: data.hasDrivingLicense,
      drivingLicenseDate: data.drivingLicenseDate,
      occupation: data.occupation,
      maritalStatus: data.maritalStatus,
      hasChildUnder26: data.hasChildUnder26,
      clientId: data.clientId,
      vehicleId: data.vehicleId,
      agentId: data.agentId,
      organizationId: data.organizationId,
      status: data.status,
      value: data.value,
      validUntil: data.validUntil,
      variant: data.variant,
      scopes: data.scopes,
      externalId: data.externalId,
      syncedAt: data.syncedAt,
      createdAt: data.createdAt,
      updatedAt: data.updatedAt,
    }
  }
}

